## Assignment 8 of python programming (basic)

In [2]:
#Q1
import numpy as np
m1 = [
    [1,2,3],
    [2,3,4],
    [3,4,5]
]

m2 = [
    [0,9,8],
    [5,6,7],
    [11,1,1]
]

m1 = np.array(m1)
m2 = np.array(m2)

print(m1+m2)

[[ 1 11 11]
 [ 7  9 11]
 [14  5  6]]


In [3]:
#q2
print(m1*m2)

[[ 0 18 24]
 [10 18 28]
 [33  4  5]]


In [7]:
#q3
print(m2.T)

[[ 0  5 11]
 [ 9  6  1]
 [ 8  7  1]]


In [21]:
#q4

def sortAlpha(word):
    a = []
    for i in range(len(word)):
        a.append(ord(word[i]))
    a.sort()
    txt = ''
    for i in range(len(a)):
        txt+=chr(a[i])
    return txt.strip()

sortAlpha('rohit')


'hiort'

In [31]:
#Q5
def remsp(word):
    a = []
    for i in range(len(word)):
        a.append(ord(word[i]))
    txt = ''
    for i in range(len(a)):
        if (a[i]>=65 and a[i]<=90) or (a[i]>=97 and a[i]<=122):
            txt+=chr(a[i])

    return txt.strip()

remsp('word,')

'word'